import './globals.css';
import type { Metadata } from 'next';

import { footerConfig } from '@/config';

import { Container } from '@/components/Container';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white-300">
        <Container>{children}</Container>
        <Footer items={footerConfig} />
      </body>
    </html>
  );
}
